# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/localadmin/caaa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/localadmin/caaa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/localadmin/caaa/CMakeFiles /home/localadmin/caaa//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/localadmin/caaa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named caaa

# Build rule for target.
caaa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 caaa
.PHONY : caaa

# fast build rule for target.
caaa/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/build
.PHONY : caaa/fast

src/canal.o: src/canal.c.o
.PHONY : src/canal.o

# target to build an object file
src/canal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/canal.c.o
.PHONY : src/canal.c.o

src/canal.i: src/canal.c.i
.PHONY : src/canal.i

# target to preprocess a source file
src/canal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/canal.c.i
.PHONY : src/canal.c.i

src/canal.s: src/canal.c.s
.PHONY : src/canal.s

# target to generate assembly for a file
src/canal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/canal.c.s
.PHONY : src/canal.c.s

src/engine.o: src/engine.c.o
.PHONY : src/engine.o

# target to build an object file
src/engine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/engine.c.o
.PHONY : src/engine.c.o

src/engine.i: src/engine.c.i
.PHONY : src/engine.i

# target to preprocess a source file
src/engine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/engine.c.i
.PHONY : src/engine.c.i

src/engine.s: src/engine.c.s
.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/engine.c.s
.PHONY : src/engine.c.s

src/game_state.o: src/game_state.c.o
.PHONY : src/game_state.o

# target to build an object file
src/game_state.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/game_state.c.o
.PHONY : src/game_state.c.o

src/game_state.i: src/game_state.c.i
.PHONY : src/game_state.i

# target to preprocess a source file
src/game_state.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/game_state.c.i
.PHONY : src/game_state.c.i

src/game_state.s: src/game_state.c.s
.PHONY : src/game_state.s

# target to generate assembly for a file
src/game_state.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/game_state.c.s
.PHONY : src/game_state.c.s

src/land.o: src/land.c.o
.PHONY : src/land.o

# target to build an object file
src/land.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/land.c.o
.PHONY : src/land.c.o

src/land.i: src/land.c.i
.PHONY : src/land.i

# target to preprocess a source file
src/land.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/land.c.i
.PHONY : src/land.c.i

src/land.s: src/land.c.s
.PHONY : src/land.s

# target to generate assembly for a file
src/land.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/land.c.s
.PHONY : src/land.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/main.c.s
.PHONY : src/main.c.s

src/mcts.o: src/mcts.c.o
.PHONY : src/mcts.o

# target to build an object file
src/mcts.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/mcts.c.o
.PHONY : src/mcts.c.o

src/mcts.i: src/mcts.c.i
.PHONY : src/mcts.i

# target to preprocess a source file
src/mcts.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/mcts.c.i
.PHONY : src/mcts.c.i

src/mcts.s: src/mcts.c.s
.PHONY : src/mcts.s

# target to generate assembly for a file
src/mcts.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/mcts.c.s
.PHONY : src/mcts.c.s

src/player.o: src/player.c.o
.PHONY : src/player.o

# target to build an object file
src/player.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/player.c.o
.PHONY : src/player.c.o

src/player.i: src/player.c.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/player.c.i
.PHONY : src/player.c.i

src/player.s: src/player.c.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/player.c.s
.PHONY : src/player.c.s

src/sea.o: src/sea.c.o
.PHONY : src/sea.o

# target to build an object file
src/sea.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/sea.c.o
.PHONY : src/sea.c.o

src/sea.i: src/sea.c.i
.PHONY : src/sea.i

# target to preprocess a source file
src/sea.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/sea.c.i
.PHONY : src/sea.c.i

src/sea.s: src/sea.c.s
.PHONY : src/sea.s

# target to generate assembly for a file
src/sea.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/sea.c.s
.PHONY : src/sea.c.s

src/serialize_data.o: src/serialize_data.c.o
.PHONY : src/serialize_data.o

# target to build an object file
src/serialize_data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/serialize_data.c.o
.PHONY : src/serialize_data.c.o

src/serialize_data.i: src/serialize_data.c.i
.PHONY : src/serialize_data.i

# target to preprocess a source file
src/serialize_data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/serialize_data.c.i
.PHONY : src/serialize_data.c.i

src/serialize_data.s: src/serialize_data.c.s
.PHONY : src/serialize_data.s

# target to generate assembly for a file
src/serialize_data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/serialize_data.c.s
.PHONY : src/serialize_data.c.s

src/team.o: src/team.c.o
.PHONY : src/team.o

# target to build an object file
src/team.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/team.c.o
.PHONY : src/team.c.o

src/team.i: src/team.c.i
.PHONY : src/team.i

# target to preprocess a source file
src/team.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/team.c.i
.PHONY : src/team.c.i

src/team.s: src/team.c.s
.PHONY : src/team.s

# target to generate assembly for a file
src/team.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/team.c.s
.PHONY : src/team.c.s

src/units.o: src/units.c.o
.PHONY : src/units.o

# target to build an object file
src/units.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/units.c.o
.PHONY : src/units.c.o

src/units.i: src/units.c.i
.PHONY : src/units.i

# target to preprocess a source file
src/units.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/units.c.i
.PHONY : src/units.c.i

src/units.s: src/units.c.s
.PHONY : src/units.s

# target to generate assembly for a file
src/units.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caaa.dir/build.make CMakeFiles/caaa.dir/src/units.c.s
.PHONY : src/units.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... caaa"
	@echo "... src/canal.o"
	@echo "... src/canal.i"
	@echo "... src/canal.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/game_state.o"
	@echo "... src/game_state.i"
	@echo "... src/game_state.s"
	@echo "... src/land.o"
	@echo "... src/land.i"
	@echo "... src/land.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mcts.o"
	@echo "... src/mcts.i"
	@echo "... src/mcts.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/sea.o"
	@echo "... src/sea.i"
	@echo "... src/sea.s"
	@echo "... src/serialize_data.o"
	@echo "... src/serialize_data.i"
	@echo "... src/serialize_data.s"
	@echo "... src/team.o"
	@echo "... src/team.i"
	@echo "... src/team.s"
	@echo "... src/units.o"
	@echo "... src/units.i"
	@echo "... src/units.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

