#ifndef ARTILLERY_H
#define ARTILLERY_H

#define ARTILLERY_NAME "artillery"
#define ARTILLERY_ATTACK 2
#define ARTILLERY_DEFENSE 2
#define ARTILLERY_MOVES_MAX 1
#define ARTILLERY_COST 4
#define ARTILLERY_WEIGHT 3
#define ARTILLERY_STATES ARTILLERY_MOVES_MAX + 1

#endif
