#ifndef CARRIER_H
#define CARRIER_H

#define CARRIER_NAME "carriers"
#define CARRIER_ATTACK 1
#define CARRIER_DEFENSE 2
#define CARRIER_MOVES_MAX 2
#define CARRIER_COST 14
#define CARRIER_STATES CARRIER_MOVES_MAX + 1

#endif
