#ifndef CRUISER_H
#define CRUISER_H

#define CRUISER_NAME "cruisers"
#define CRUISER_ATTACK 3
#define CRUISER_DEFENSE 3
#define CRUISER_MOVES_MAX 2
#define CRUISER_COST 10
#define CRUISER_STATES CRUISER_MOVES_MAX + 1

#endif
