#ifndef DESTROYER_H
#define DESTROYER_H

#define DESTROYER_NAME "destroyers"
#define DESTROYER_ATTACK 2
#define DESTROYER_DEFENSE 2
#define DESTROYER_MOVES_MAX 2
#define DESTROYER_COST 8
#define DESTROYER_STATES DESTROYER_MOVES_MAX + 1

#endif
