#ifndef TRANSPORT_H
#define TRANSPORT_H

#define TRANSPORT_NAME "tran_empty"
#define TRANSPORT_ATTACK 0
#define TRANSPORT_DEFENSE 0
#define TRANSPORT_MOVES_MAX 2
#define TRANSPORT_COST 8
#define TRANSPORT_CARRY_LAND 5

#define TRANS_EMPTY_STATES TRANSPORT_MOVES_MAX + 2
#define TRANS_1I_NAME "tran_1i"
#define TRANS_1I_STATES TRANSPORT_MOVES_MAX + 3
#define TRANS_1A_NAME "tran_1a"
#define TRANS_1A_STATES TRANSPORT_MOVES_MAX + 3
#define TRANS_1T_NAME "tran_1t"
#define TRANS_1T_STATES TRANSPORT_MOVES_MAX + 3
#define TRANS_2I_NAME "tran_2i"
#define TRANS_2I_STATES TRANSPORT_MOVES_MAX + 2
#define TRANS_1I_1A_NAME "tran_1i_1a"
#define TRANS_1I_1A_STATES TRANSPORT_MOVES_MAX + 2
#define TRANS_1I_1T_NAME "tran_1i_1t"
#define TRANS_1I_1T_STATES TRANSPORT_MOVES_MAX + 2

#endif
