#ifndef BATTLESHIP_H
#define BATTLESHIP_H

#define BATTLESHIP_NAME "Battleship"
#define BATTLESHIP_ATTACK 4
#define BATTLESHIP_DEFENSE 4
#define BATTLESHIP_MOVES_MAX 2
#define BATTLESHIP_COST 20

#endif
