#ifndef CONFIG_H
#define CONFIG_H
#define CONNECTIONS_COUNT 2
#define PLAYERS_COUNT 2
#define MAX_CARGO_COUNT 2
#define MAX_LAND_TO_LAND_CONNECTIONS 1
#define MAX_LAND_TO_SEA_CONNECTIONS 2
#define MAX_SEA_TO_LAND_CONNECTIONS 2
#define MAX_SEA_TO_SEA_CONNECTIONS 1
#define MAX_TEAM_SIZE 1
#define MOBILE_UNITS_COUNT 1
#define SEAS_COUNT 2
#define TEAMS_COUNT 2
#define TERRITORIES_COUNT 4
#define UNIT_HEALTHS_COUNT 1
#define UNIT_TYPES_COUNT 1
#endif