#ifndef CONFIG_H
#define CONFIG_H
#define LANDS_COUNT 5
#define MAX_CARGO_COUNT 2
#define MAX_LAND_TO_LAND_CONNECTIONS 6
#define MAX_LAND_TO_SEA_CONNECTIONS 4
#define MAX_SEA_TO_LAND_CONNECTIONS 6
#define MAX_SEA_TO_SEA_CONNECTIONS 7
#define MAX_TEAM_SIZE 3
#define PLAYERS_COUNT 5
#define SEAS_COUNT 3
#define TEAMS_COUNT 2
#endif